// Package or registers the or tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package or

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed or.names.bin
var f0 []byte

//go:embed or.words.bin
var f1 []byte

func init() {
	romanize.Register("or.names.bin", f0)
	romanize.Register("or.words.bin", f1)
}
