// Package gu registers the gu tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package gu

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed gu.names.bin
var f0 []byte

//go:embed gu.words.bin
var f1 []byte

func init() {
	romanize.Register("gu.names.bin", f0)
	romanize.Register("gu.words.bin", f1)
}
