// Package kn registers the kn tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package kn

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed kn.names.bin
var f0 []byte

//go:embed kn.words.bin
var f1 []byte

func init() {
	romanize.Register("kn.names.bin", f0)
	romanize.Register("kn.words.bin", f1)
}
