// Package sat registers the sat tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package sat

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/olchiki"
)

//go:embed sat.names.bin
var f0 []byte

func init() {
	romanize.Register("sat.names.bin", f0)
}
