// Package ne registers the ne tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package ne

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed ne.list.bin
var f0 []byte

//go:embed ne.names-list.bin
var f1 []byte

//go:embed ne.names.bin
var f2 []byte

//go:embed ne.words.bin
var f3 []byte

func init() {
	deromanize.Register("ne.list.bin", f0)
	deromanize.Register("ne.names-list.bin", f1)
	deromanize.Register("ne.names.bin", f2)
	deromanize.Register("ne.words.bin", f3)
}
