// Package pa registers the pa tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package pa

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed pa.names.bin
var f0 []byte

//go:embed pa.words.bin
var f1 []byte

func init() {
	romanize.Register("pa.names.bin", f0)
	romanize.Register("pa.words.bin", f1)
}
