// Package ur registers the ur tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package ur

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/arabic"
)

//go:embed ur.list.bin
var f0 []byte

//go:embed ur.names-list.bin
var f1 []byte

//go:embed ur.names.bin
var f2 []byte

//go:embed ur.words.bin
var f3 []byte

func init() {
	deromanize.Register("ur.list.bin", f0)
	deromanize.Register("ur.names-list.bin", f1)
	deromanize.Register("ur.names.bin", f2)
	deromanize.Register("ur.words.bin", f3)
}
