// Package te registers the te tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package te

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed te.names.bin
var f0 []byte

//go:embed te.words.bin
var f1 []byte

func init() {
	romanize.Register("te.names.bin", f0)
	romanize.Register("te.words.bin", f1)
}
