// Package ks registers the ks tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package ks

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/arabic"
)

//go:embed ks.names.bin
var f0 []byte

//go:embed ks.words.bin
var f1 []byte

func init() {
	romanize.Register("ks.names.bin", f0)
	romanize.Register("ks.words.bin", f1)
}
