// Package mr registers the mr tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package mr

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed mr.names.bin
var f0 []byte

//go:embed mr.words.bin
var f1 []byte

func init() {
	romanize.Register("mr.names.bin", f0)
	romanize.Register("mr.words.bin", f1)
}
