// Package sa registers the sa tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package sa

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed sa.names.bin
var f0 []byte

//go:embed sa.words.bin
var f1 []byte

func init() {
	romanize.Register("sa.names.bin", f0)
	romanize.Register("sa.words.bin", f1)
}
