// Package ta registers the ta tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package ta

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed ta.list.bin
var f0 []byte

//go:embed ta.names-list.bin
var f1 []byte

//go:embed ta.names.bin
var f2 []byte

//go:embed ta.words.bin
var f3 []byte

func init() {
	deromanize.Register("ta.list.bin", f0)
	deromanize.Register("ta.names-list.bin", f1)
	deromanize.Register("ta.names.bin", f2)
	deromanize.Register("ta.words.bin", f3)
}
