// Package ml registers the ml tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package ml

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed ml.names.bin
var f0 []byte

//go:embed ml.words.bin
var f1 []byte

func init() {
	romanize.Register("ml.names.bin", f0)
	romanize.Register("ml.words.bin", f1)
}
