// Package ta registers the ta tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package ta

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed ta.names.bin
var f0 []byte

//go:embed ta.words.bin
var f1 []byte

func init() {
	romanize.Register("ta.names.bin", f0)
	romanize.Register("ta.words.bin", f1)
}
