// Package sa registers the sa tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package sa

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed sa.list.bin
var f0 []byte

//go:embed sa.names-list.bin
var f1 []byte

//go:embed sa.names.bin
var f2 []byte

//go:embed sa.words.bin
var f3 []byte

func init() {
	deromanize.Register("sa.list.bin", f0)
	deromanize.Register("sa.names-list.bin", f1)
	deromanize.Register("sa.names.bin", f2)
	deromanize.Register("sa.words.bin", f3)
}
