// Package kn registers the kn tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package kn

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed kn.list.bin
var f0 []byte

//go:embed kn.names-list.bin
var f1 []byte

//go:embed kn.names.bin
var f2 []byte

//go:embed kn.words.bin
var f3 []byte

func init() {
	deromanize.Register("kn.list.bin", f0)
	deromanize.Register("kn.names-list.bin", f1)
	deromanize.Register("kn.names.bin", f2)
	deromanize.Register("kn.words.bin", f3)
}
