// Package brx registers the brx tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package brx

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed brx.words.bin
var f0 []byte

func init() {
	romanize.Register("brx.words.bin", f0)
}
