// Package ne registers the ne tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package ne

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed ne.names.bin
var f0 []byte

//go:embed ne.words.bin
var f1 []byte

func init() {
	romanize.Register("ne.names.bin", f0)
	romanize.Register("ne.words.bin", f1)
}
