// Package ml registers the ml tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package ml

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed ml.list.bin
var f0 []byte

//go:embed ml.names-list.bin
var f1 []byte

//go:embed ml.names.bin
var f2 []byte

//go:embed ml.words.bin
var f3 []byte

func init() {
	deromanize.Register("ml.list.bin", f0)
	deromanize.Register("ml.names-list.bin", f1)
	deromanize.Register("ml.names.bin", f2)
	deromanize.Register("ml.words.bin", f3)
}
