// Package mni registers the mni tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package mni

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/meetei"
)

//go:embed mni.names.bin
var f0 []byte

//go:embed mni.words.bin
var f1 []byte

func init() {
	romanize.Register("mni.names.bin", f0)
	romanize.Register("mni.words.bin", f1)
}
