// Package sd registers the sd tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package sd

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/arabic"
)

//go:embed sd.list.bin
var f0 []byte

//go:embed sd.names-list.bin
var f1 []byte

//go:embed sd.names.bin
var f2 []byte

//go:embed sd.words.bin
var f3 []byte

func init() {
	deromanize.Register("sd.list.bin", f0)
	deromanize.Register("sd.names-list.bin", f1)
	deromanize.Register("sd.names.bin", f2)
	deromanize.Register("sd.words.bin", f3)
}
