// Package brahmic holds the brahmic script group's pooled tables; each language of the group imports it.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package brahmic

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
)

//go:embed names-brahmic.bin
var f0 []byte

//go:embed words-brahmic.bin
var f1 []byte

func init() {
	romanize.Register("names-brahmic.bin", f0)
	romanize.Register("words-brahmic.bin", f1)
}
