// Package sd registers the sd tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package sd

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/arabic"
)

//go:embed sd.names.bin
var f0 []byte

//go:embed sd.words.bin
var f1 []byte

func init() {
	romanize.Register("sd.names.bin", f0)
	romanize.Register("sd.words.bin", f1)
}
