// Package gu registers the gu tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package gu

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed gu.list.bin
var f0 []byte

//go:embed gu.names-list.bin
var f1 []byte

//go:embed gu.names.bin
var f2 []byte

//go:embed gu.words.bin
var f3 []byte

func init() {
	deromanize.Register("gu.list.bin", f0)
	deromanize.Register("gu.names-list.bin", f1)
	deromanize.Register("gu.names.bin", f2)
	deromanize.Register("gu.words.bin", f3)
}
