// Package olchiki holds the olchiki script group's pooled tables; each language of the group imports it.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package olchiki

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
)

//go:embed names-olchiki.bin
var f0 []byte

func init() {
	romanize.Register("names-olchiki.bin", f0)
}
