// Package as registers the as tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package as

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed as.names.bin
var f0 []byte

//go:embed as.words.bin
var f1 []byte

func init() {
	romanize.Register("as.names.bin", f0)
	romanize.Register("as.words.bin", f1)
}
