// Package bn registers the bn tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package bn

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed bn.names.bin
var f0 []byte

//go:embed bn.words.bin
var f1 []byte

func init() {
	romanize.Register("bn.names.bin", f0)
	romanize.Register("bn.words.bin", f1)
}
