// Package mai registers the mai tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package mai

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed mai.list.bin
var f0 []byte

//go:embed mai.names-list.bin
var f1 []byte

//go:embed mai.names.bin
var f2 []byte

//go:embed mai.words.bin
var f3 []byte

func init() {
	deromanize.Register("mai.list.bin", f0)
	deromanize.Register("mai.names-list.bin", f1)
	deromanize.Register("mai.names.bin", f2)
	deromanize.Register("mai.words.bin", f3)
}
