// Package or registers the or tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package or

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed or.list.bin
var f0 []byte

//go:embed or.names-list.bin
var f1 []byte

//go:embed or.names.bin
var f2 []byte

//go:embed or.words.bin
var f3 []byte

func init() {
	deromanize.Register("or.list.bin", f0)
	deromanize.Register("or.names-list.bin", f1)
	deromanize.Register("or.names.bin", f2)
	deromanize.Register("or.words.bin", f3)
}
