// Package mni registers the mni tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package mni

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/meetei"
)

//go:embed mni.list.bin
var f0 []byte

//go:embed mni.names-list.bin
var f1 []byte

//go:embed mni.names.bin
var f2 []byte

//go:embed mni.words.bin
var f3 []byte

func init() {
	deromanize.Register("mni.list.bin", f0)
	deromanize.Register("mni.names-list.bin", f1)
	deromanize.Register("mni.names.bin", f2)
	deromanize.Register("mni.words.bin", f3)
}
