// Package as registers the as tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package as

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed as.list.bin
var f0 []byte

//go:embed as.names-list.bin
var f1 []byte

//go:embed as.names.bin
var f2 []byte

//go:embed as.words.bin
var f3 []byte

func init() {
	deromanize.Register("as.list.bin", f0)
	deromanize.Register("as.names-list.bin", f1)
	deromanize.Register("as.names.bin", f2)
	deromanize.Register("as.words.bin", f3)
}
