// Package gom registers the gom tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package gom

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed gom.names.bin
var f0 []byte

//go:embed gom.words.bin
var f1 []byte

func init() {
	romanize.Register("gom.names.bin", f0)
	romanize.Register("gom.words.bin", f1)
}
