// Package bn registers the bn tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package bn

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed bn.list.bin
var f0 []byte

//go:embed bn.names-list.bin
var f1 []byte

//go:embed bn.names.bin
var f2 []byte

//go:embed bn.words.bin
var f3 []byte

func init() {
	deromanize.Register("bn.list.bin", f0)
	deromanize.Register("bn.names-list.bin", f1)
	deromanize.Register("bn.names.bin", f2)
	deromanize.Register("bn.words.bin", f3)
}
