// Package mr registers the mr tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package mr

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed mr.list.bin
var f0 []byte

//go:embed mr.names-list.bin
var f1 []byte

//go:embed mr.names.bin
var f2 []byte

//go:embed mr.words.bin
var f3 []byte

func init() {
	deromanize.Register("mr.list.bin", f0)
	deromanize.Register("mr.names-list.bin", f1)
	deromanize.Register("mr.names.bin", f2)
	deromanize.Register("mr.words.bin", f3)
}
