// Package doi registers the doi tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package doi

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed doi.words.bin
var f0 []byte

func init() {
	romanize.Register("doi.words.bin", f0)
}
