// Package brx registers the brx tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package brx

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed brx.list.bin
var f0 []byte

//go:embed brx.words.bin
var f1 []byte

func init() {
	deromanize.Register("brx.list.bin", f0)
	deromanize.Register("brx.words.bin", f1)
}
