// Package mai registers the mai tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package mai

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed mai.names.bin
var f0 []byte

//go:embed mai.words.bin
var f1 []byte

func init() {
	romanize.Register("mai.names.bin", f0)
	romanize.Register("mai.words.bin", f1)
}
