// Package doi registers the doi tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package doi

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed doi.list.bin
var f0 []byte

//go:embed doi.words.bin
var f1 []byte

func init() {
	deromanize.Register("doi.list.bin", f0)
	deromanize.Register("doi.words.bin", f1)
}
