// Package hi registers the hi tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package hi

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed hi.list.bin
var f0 []byte

//go:embed hi.names-list.bin
var f1 []byte

//go:embed hi.names.bin
var f2 []byte

//go:embed hi.words.bin
var f3 []byte

func init() {
	deromanize.Register("hi.list.bin", f0)
	deromanize.Register("hi.names-list.bin", f1)
	deromanize.Register("hi.names.bin", f2)
	deromanize.Register("hi.words.bin", f3)
}
