// Package pa registers the pa tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package pa

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed pa.list.bin
var f0 []byte

//go:embed pa.names-list.bin
var f1 []byte

//go:embed pa.names.bin
var f2 []byte

//go:embed pa.words.bin
var f3 []byte

func init() {
	deromanize.Register("pa.list.bin", f0)
	deromanize.Register("pa.names-list.bin", f1)
	deromanize.Register("pa.names.bin", f2)
	deromanize.Register("pa.words.bin", f3)
}
