// Package arabic holds the arabic script group's pooled tables; each language of the group imports it.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package arabic

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
)

//go:embed names-arabic.bin
var f0 []byte

//go:embed words-arabic.bin
var f1 []byte

func init() {
	romanize.Register("names-arabic.bin", f0)
	romanize.Register("words-arabic.bin", f1)
}
