// Package meetei holds the meetei script group's pooled tables; each language of the group imports it.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package meetei

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
)

//go:embed names-meetei.bin
var f0 []byte

//go:embed words-meetei.bin
var f1 []byte

func init() {
	romanize.Register("names-meetei.bin", f0)
	romanize.Register("words-meetei.bin", f1)
}
