// Package hi registers the hi tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package hi

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/brahmic"
)

//go:embed hi.names.bin
var f0 []byte

//go:embed hi.words.bin
var f1 []byte

func init() {
	romanize.Register("hi.names.bin", f0)
	romanize.Register("hi.words.bin", f1)
}
