// Package te registers the te tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package te

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed te.list.bin
var f0 []byte

//go:embed te.names-list.bin
var f1 []byte

//go:embed te.names.bin
var f2 []byte

//go:embed te.words.bin
var f3 []byte

func init() {
	deromanize.Register("te.list.bin", f0)
	deromanize.Register("te.names-list.bin", f1)
	deromanize.Register("te.names.bin", f2)
	deromanize.Register("te.words.bin", f3)
}
