// Package ur registers the ur tables: import it for its side effect.
//
// Generated by linguistic-utilities jobs/romanize/export.py; do not edit.
package ur

import (
	_ "embed"

	"github.com/micahchoo/indickit/romanize"
	_ "github.com/micahchoo/indickit/romanize/lang/arabic"
)

//go:embed ur.names.bin
var f0 []byte

//go:embed ur.words.bin
var f1 []byte

func init() {
	romanize.Register("ur.names.bin", f0)
	romanize.Register("ur.words.bin", f1)
}
