// Package gom registers the gom tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package gom

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/brahmic"
)

//go:embed gom.list.bin
var f0 []byte

//go:embed gom.names-list.bin
var f1 []byte

//go:embed gom.names.bin
var f2 []byte

//go:embed gom.words.bin
var f3 []byte

func init() {
	deromanize.Register("gom.list.bin", f0)
	deromanize.Register("gom.names-list.bin", f1)
	deromanize.Register("gom.names.bin", f2)
	deromanize.Register("gom.words.bin", f3)
}
