// Package sat registers the sat tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package sat

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/olchiki"
)

//go:embed sat.list.bin
var f0 []byte

//go:embed sat.names-list.bin
var f1 []byte

//go:embed sat.names.bin
var f2 []byte

func init() {
	deromanize.Register("sat.list.bin", f0)
	deromanize.Register("sat.names-list.bin", f1)
	deromanize.Register("sat.names.bin", f2)
}
