// Package ks registers the ks tables and word list: import it for its side effect.
//
// Generated by linguistic-utilities jobs/deromanize/export.py; do not edit.
package ks

import (
	_ "embed"

	"github.com/micahchoo/indickit/deromanize"
	_ "github.com/micahchoo/indickit/deromanize/lang/arabic"
)

//go:embed ks.list.bin
var f0 []byte

//go:embed ks.names-list.bin
var f1 []byte

//go:embed ks.names.bin
var f2 []byte

//go:embed ks.words.bin
var f3 []byte

func init() {
	deromanize.Register("ks.list.bin", f0)
	deromanize.Register("ks.names-list.bin", f1)
	deromanize.Register("ks.names.bin", f2)
	deromanize.Register("ks.words.bin", f3)
}
